SET IDENTITY_INSERT [dbo].[Recipient] ON
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (1, N'Naruto Uzamaki', 20, N'B+', N'###2090745', N'Nine-tailed Beast')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (2, N'Saukra Haruno', 22, N'B+', N'####090334', N'Medical Ninja')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (3, N'Kakashi Hatake', 34, N'O+', N'####090332', N'One eyed')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (4, N'Sasuke Uchiha', 24, N'AB+', N'####090321', N'Sharingan')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (6, N'Shikamaru Nara', 23, N'A+', N'###2090567', N'Generally healthy')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (7, N'Ino Yamanaka', 23, N'O-', N'###2090987', N'Prone to allergies')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (8, N'Choji Akimichi', 24, N'B-', N'###2090221', N'Needs to watch diet')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (9, N'Neji Hyuga', 24, N'A+', N'###2090456', N'Fully recovered from past injuries')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (10, N'Rock Lee', 21, N'O+', N'###2090123', N'Recovering from intense training')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (11, N'Tenten', 22, N'B+', N'###2090256', N'Has minor cuts and bruises')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (12, N'Kiba Inuzuka', 23, N'A+', N'###2090876', N'Has a cold')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (13, N'Shino Aburame', 22, N'O-', N'###2090321', N'Allergic reaction to bugs')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (14, N'Choza Akimichi', 43, N'A+', N'###2090345', N'High blood pressure')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (15, N'Asuma Sarutobi', 28, N'AB+', N'###2090678', N'Smoker')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (16, N'Hiruzen Sarutobi', 68, N'O+', N'###2090456', N'Old age-related issues')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (17, N'Tsunade', 52, N'B-', N'###2090234', N'Arthritis')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (18, N'Jiraiya', 54, N'O+', N'###2090789', N'Injured back')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (19, N'Orochimaru', 54, N'AB-', N'###2090876', N'Experiments gone wrong')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (20, N'Konohamaru Sarutobi', 14, N'O+', N'###2090999', N'Flu')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (21, N'Sai', 18, N'B+', N'###2090888', N'Minor wounds')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (22, N'Yamato', 31, N'O+', N'###2090777', N'Minor illness')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (23, N'Killer Bee', 36, N'B+', N'###2090666', N'Physical exhaustion')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (24, N'Gaara', 24, N'O+', N'###2090555', N'Minor sand injuries')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (25, N'Temari', 26, N'B+', N'###2090444', N'Fatigue')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (26, N'Kankuro', 24, N'B-', N'###2090333', N'Worn-out puppets')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (27, N'Kurenai Yuhi', 30, N'O-', N'###2090222', N'Stress-related headaches')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (28, N'Hidan', 22, N'O-', N'###2090111', N'Body pains')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (29, N'Kakuzu', 91, N'AB+', N'###2090900', N'Old age ailments')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (30, N'Yahiko', 22, N'O+', N'###2090999', N'Cold')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (31, N'Konan', 21, N'A-', N'###2090888', N'Minor injuries')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (32, N'Obito Uchiha', 33, N'O+', N'###2090777', N'Vision issues')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (33, N'Danzo Shimura', 71, N'O-', N'###2090666', N'Heart problems')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (34, N'Mei Terumi', 34, N'AB-', N'###2090555', N'Minor injuries')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (35, N'Onoki', 79, N'O-', N'###2090444', N'Old age-related ailments')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (36, N'Gengetsu Hozuki', 34, N'O+', N'###2090333', N'Physical exhaustion')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (37, N'Rasa', 49, N'O-', N'###2090222', N'Joint pains')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (38, N'Boruto Uzamaki', 19, N'A+', N'###2090111', N'Fatigue')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (39, N'Killer B', 36, N'B+', N'###2090000', N'Overexertion')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (40, N'Omoi', 23, N'O-', N'###2090001', N'Allergic reaction')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (41, N'Karui', 24, N'B-', N'###2090002', N'Joint stiffness')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (42, N'Sarad Uchiha', 25, N'AB+', N'###2090003', N'Chronic illness')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (43, N'Hakamaru', 22, N'O+', N'###2090004', N'Cold symptoms')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (44, N'Saruto Uzamaki', 24, N'A-', N'###2090005', N'Wound healing')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (45, N'Akamichi', 29, N'O-', N'###2090006', N'Back pain')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (46, N'Udon', 28, N'A+', N'###2090007', N'Sleep deprivation')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (47, N'Ichiraku', 27, N'O+', N'###2090008', N'Minor illness')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (48, N'Shojen', 26, N'B+', N'###2090009', N'Stress-related ailments')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (49, N'Mangekyo', 25, N'B-', N'###2090010', N'Injury recovery')
INSERT INTO [dbo].[Recipient] ([RecipientId], [RecipientName], [Age], [BloodType], [Contact], [MedicalCondition]) VALUES (51, N'Kaguya', 24, N'O+', N'###2090011', N'fever')
SET IDENTITY_INSERT [dbo].[Recipient] OFF
